version: '3'

services:
  nginx:
    image: nginx:1.22.1
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    restart: always

  mariadb:
    image: mariadb:10.6.12
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    ports:
      - 3306:3306
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    restart: always

  wordpress:
    image: wordpress:6.1.1
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    ports:
      - 9000:9000
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    restart: always

volumes:
  wordpress:
    driver: local
    driver_opts:
      device: ${HOME}/data/WordPress
      type: none
      o: bind
  mariadb:
    driver: local
    driver_opts:
      device: ${HOME}/data/DB
      type: none
      o: bind

networks:
  inception:
    driver: bridge

# networks : 단일 네트워크를 정의. 새로운 Docker bridge 생성. 인스턴스를 생성할 때 해당 네트워크를 사용할 수 있으며 컨테이너들이 inception 네트워크에 참여할 수 있게 지시하여 다른 컨테이너들과 통신할 수 있다.(원래는 격리된 공간들 이기 때문에)
# volumes : host 머신과 바인딩(실시간으로 파일들을 공유) 하기 위해서 설정해준다. 컨테이너를 삭제하고 다시 생성할 때, 이전 상태를 복원하거나 수정하기 용이하다.
# driver : local(host)
# type : local default
# o : mount 시 추가적인 옵션을 설정할 수 있는 파라미터. 해당 파일에선 bind 옵션을 준거다.
